#!/bin/bash
#get the directy name of the 
DIR="$( cd "$( dirname "$0" )" && pwd )"

#change the name of the dependency libxl.dylib by its absolute path
LIB=`echo ${DIR}/exe/libxl.dylib`
OLDLIB=`otool -L ${DIR}/exe/main | grep "libxl.dylib" | cut -d" " -f1`
install_name_tool -change ${OLDLIB} ${LIB} ${DIR}/exe/main

#execute the binary
${DIR}/exe/main