version: 0.1.{build}

os: Windows Server 2012 R2

platform: x64

environment:
  matrix:
  - TOOLCHAIN: "cygwin"

branches:
  only:
    - dev
    - master

clone_folder: c:\projects\libxls

skip_tags: true

build_script:
  - C:\cygwin64\setup-x86_64.exe -qP autoconf-archive
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/libxls && ./bootstrap"
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/libxls && ./configure"
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/libxls && make"

test_script:
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/libxls && make check"
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/libxls && ./test2_libxls test/files/test2.xls"

on_finish:
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/libxls && cat ./test-suite.log"
