#Compilation flags
CFLAGS = -Wall -o

#Libraries

#C files
ALL_FILES = main.c ../libraries/libxls/src/xls.c ../libraries/libxls/src/xlstools.c

#Executable name
EXE = main

program:
	gcc $(CFLAGS) $(EXE) $(ALL_FILES) 
