#Compilation flags
CFLAGS = -Wall -o

#Libraries

#C files
ALL_FILES = main.c ../libraries/libxls/src/xls.c ../libraries/libxls/src/xlstool.c ../libraries/libxls/src/endian.c ../libraries/libxls/src/locale.c ../libraries/libxls/src/ole.c ../libraries/libxls/src/xls2csv.c

#Executable name
EXE = main

program:
	gcc $(CFLAGS) $(EXE) $(ALL_FILES)
