name: build
on: [ push, pull_request ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ clang, gcc, gcc-8, gcc-9, gcc-10 ]
    steps:
      - name: Add repository
        run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      - name: Install packages
        run: sudo apt install gettext autoconf-archive
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Run tests
        run: make check
      - name: Run test program
        run: ./test2_libxls test/files/test2.xls
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ clang, gcc ]
    steps:
      - name: Install packages
        run: brew install automake autoconf-archive
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Run tests
        run: make check
      - name: Run test program
        run: ./test2_libxls test/files/test2.xls
  windows:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && pacman -S --noconfirm autoconf-archive'
      - name: Autoconf
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && autoreconf -i -f'
      - name: Configure
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && ./configure'
      - name: Make
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && make'
      - name: Test
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && make check'
      - name: Test
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && ./test2_libxls test/files/test2.xls'
      - name: Log
        run: C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE" && cat ./test-suite.log'
